version: "3.9"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (non-TLS)
      - "5671:5671"     # AMQP over TLS
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq/certs:/certs:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  mongodbStandalone:
    image: mongo:6.0
    container_name: mongodbStandalone
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    environment:
      - EVENTSTORE_DB=eventstore
      - EVENTSTORE_INSECURE=true         # Disable TLS for local dev (DO NOT use in production)
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=false
      - EVENTSTORE_LOG_LEVEL=Information
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113        # HTTP + gRPC port
    ports:
      - "1113:1113"   # TCP for legacy client protocol
      - "2113:2113"   # HTTP + gRPC endpoint
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongodbStandalone
    depends_on:
      - mongodbStandalone

  consolicationservice:
    build:
      context: ./ConsolicationService
      dockerfile: Dockerfile
    container_name: consolicationservice
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__HostName: rabbitmq
      MongoDb__ConnectionString: mongodb://root:1234@mongodbStandalone:27017
      EventStore__ConnectionString: esdb://eventstore:2113?tls=false
    depends_on:
      - rabbitmq
      - mongodbStandalone
      - eventstore

  transactionservice:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile
    container_name: transactionservice
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__HostName: rabbitmq
      MongoDb__ConnectionString: mongodb://root:1234@mongodbStandalone:27017
      EventStore__ConnectionString: esdb://eventstore:2113?tls=false
    depends_on:
      - rabbitmq
      - mongodbStandalone
      - eventstore

volumes:
  db_data: